# Make sure to check the documentation at https://goreleaser.com
project_name: switchbot-plug-exporter
before:
  hooks:
    - go mod tidy
builds:
  - env:
      # - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "rw21/{{ .ProjectName }}:{{ .Version }}-linux-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"

  - goos: linux
    goarch: arm64
    use: buildx
    image_templates:
      - "rw21/{{ .ProjectName }}:{{ .Version }}-linux-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"


docker_manifests:
  - name_template: rw21/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - "rw21/{{ .ProjectName }}:{{ .Version }}-linux-amd64"
      - "rw21/{{ .ProjectName }}:{{ .Version }}-linux-arm64"
checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: RW21
    name: switchbot-plug-exporter