# Make sure to check the documentation at https://goreleaser.com
project_name: switchbot-plug-exporter
before:
  hooks:
    - go mod tidy
builds:
  - env:
      # - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "rw21/{{ .ProjectName }}:{{ .Version }}-linux-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"

  - goos: linux
    goarch: arm64
    image_templates:
      - "rw21/{{ .ProjectName }}:{{ .Version }}-linux-arm64"
    build_flag_templates:
      - "--platform=linux/arm/v6"

  - goos: darwin
    goarch: arm64
    image_templates:
      - "rw21/{{ .ProjectName }}:{{ .Version }}-darwin-arm64"

  - goos: darwin
    goarch: amd64
    image_templates:
      - "rw21/{{ .ProjectName }}:{{ .Version }}-darwin-amd64"

docker_manifests:
  - name_template: rw21/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - "rw21/{{ .ProjectName }}:{{ .Version }}-linux-amd64"
      - "rw21/{{ .ProjectName }}:{{ .Version }}-linux-arm64"
      - "rw21/{{ .ProjectName }}:{{ .Version }}-darwin-arm64"
      - "rw21/{{ .ProjectName }}:{{ .Version }}-darwin-amd64"
checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: RW21
    name: switchbot-plug-exporter